version: "3.9"
services:
  spring-solr:
    container_name: spring-solr
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
  solr_v9:
    container_name: solr_v9
    image: solr:9.4.0-slim
    ports:
      - "8983:8983"
    volumes:
        - solr_data:/var/solr
    command:
      - solr-precreate
      - solr_core
volumes:
  solr_data: